# Convolutional Neural Network

### Importing the libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.preprocessing.image import ImageDataGenerator

In [2]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Preprocessing the Training set

In [3]:
train_datagen = ImageDataGenerator(rescale = 1./255,
#                                    shear_range = 0.2,
#                                    zoom_range = 0.2,
#                                    horizontal_flip = True
                                  rotation_range=20,           # Rotate the image by up to 20 degrees
    width_shift_range=0.2,       # Shift the image horizontally by up to 20% of the image width
    height_shift_range=0.2,      # Shift the image vertically by up to 20% of the image height
    shear_range=0.2,             # Shear the image by up to 20 degrees
    zoom_range=0.2,              # Zoom in or out on the image by up to 20%
    horizontal_flip=True,        # Flip the image horizontally
    fill_mode='nearest'
                                  
                                  )


training_set = train_datagen.flow_from_directory(r'trainset\small_sores',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 13 images belonging to 3 classes.


### Preprocessing the Test set

In [4]:
# test_datagen = ImageDataGenerator(rescale = 1./255)
# test_set = test_datagen.flow_from_directory(r'testset\rashes',
#                                             target_size = (64, 64),
#                                             batch_size = 32,
#                                             class_mode = 'categorical')

## Part 2 - Building the CNN

### Initialising the CNN

In [5]:
cnn = tf.keras.models.Sequential()



### Step 1 - Convolution

In [6]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

### Step 2 - Pooling

In [7]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Adding a second convolutional layer

In [8]:
cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Step 3 - Flattening

In [9]:
cnn.add(tf.keras.layers.Flatten())

### Step 4 - Full Connection

In [10]:
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Step 5 - Output Layer

In [11]:
cnn.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the CNN

### Compiling the CNN

In [12]:
cnn.compile(loss = 'categorical_crossentropy', optimizer = 'adam', 
              metrics = ['accuracy'])

### Training the CNN on the Training set and evaluating it on the Test set

In [13]:
import os

dir_path = r'C:\Users\Geetha\Desktop\std_severity\trainset\small_sores'

# Get a list of all the files in the directory
file_list = os.listdir(dir_path)

# Loop through the files and delete any with the ".ini" extension
for file_name in file_list:
    if file_name.endswith('.ini'):
        file_path = os.path.join(dir_path, file_name)
        os.remove(file_path)
#os.remove(r'C:\Users\Geetha\Desktop\STD_CNN\testset\muscle_wasting\desktop.ini')
#os.remove(r'C:\Users\Geetha\Desktop\STD_CNN\testset\yellowing_skin\desktop.ini')


In [14]:
import os
import cv2
bad_list=[]
dir=r'C:\Users\Geetha\Desktop\std_severity\trainset\small_sores'
subdir_list=os.listdir(dir)
for d in subdir_list:  
    dpath=os.path.join (dir, d) 
    if d in ['testset', 'trainset']:
        class_list=os.listdir(dpath) 
       # print (class_list)
        for klass in class_list: 
            class_path=os.path.join(dpath, klass) 
            #print(class_path)
            file_list=os.listdir(class_path) 
            for f in file_list: 
                fpath=os.path.join (class_path,f)
                index=f.rfind('.') 
                ext=f[index+1:] 
                if ext  not in ['jpg', 'png', 'bmp', 'gif']:
                    print(f'file {fpath}  has an invalid extension {ext}')
                    bad_list.append(fpath)                    
                else:
                    try:
                        img=cv2.imread(fpath)
                        size=img.shape
                    except:
                        print(f'file {fpath} is not a valid image file ')
                        bad_list.append(fpath)
                       
print (bad_list)

[]


In [25]:
cnn.fit(x = training_set, epochs = 25)


Epoch 1/25
1/1 [==============================] - 0s 189ms/step - loss: 0.4064 - accuracy: 0.8462
Epoch 2/25
1/1 [==============================] - 0s 147ms/step - loss: 0.2636 - accuracy: 0.9231
Epoch 3/25
1/1 [==============================] - 0s 159ms/step - loss: 0.2230 - accuracy: 0.9231
Epoch 4/25
1/1 [==============================] - 0s 226ms/step - loss: 0.3521 - accuracy: 0.9231
Epoch 5/25
1/1 [==============================] - 0s 159ms/step - loss: 0.4060 - accuracy: 0.8462
Epoch 6/25
1/1 [==============================] - 0s 246ms/step - loss: 0.2399 - accuracy: 0.9231
Epoch 7/25
1/1 [==============================] - 0s 216ms/step - loss: 0.1768 - accuracy: 1.0000
Epoch 8/25
1/1 [==============================] - 0s 165ms/step - loss: 0.2018 - accuracy: 1.0000
Epoch 9/25
1/1 [==============================] - 0s 165ms/step - loss: 0.3790 - accuracy: 0.8462
Epoch 10/25
1/1 [==============================] - 0s 134ms/step - loss: 0.2381 - accuracy: 0.9231
Epoch 11/25
1/1 [==

In [26]:

class_indices = training_set.class_indices
print(class_indices)

# Get the class label for a particular class




{'mild': 0, 'moderate': 1, 'very severe': 2}


## Part 4 - Making a single prediction

In [27]:
import numpy as np
from tensorflow.keras.utils import load_img, img_to_array
from keras.preprocessing import image
test_image = tf.keras.utils.load_img('single_prediction/mild_sores.jpg', target_size = (64, 64))
test_image = tf.keras.preprocessing.image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
print(result)
training_set.class_indices
if result[0][0] >result[0][1] and result[0][0] >result[0][2]:
  prediction = 'mild'
elif result[0][1] >result[0][0] and result[0][1] >result[0][2]:
  prediction = 'moderate'
elif result[0][2] >result[0][0] and result[0][2] >result[0][1]:
  prediction = 'very severe'



probs = cnn.predict(test_image)
print(probs)

prob_sum = np.sum(probs)
print(prob_sum)

indices=np.argsort(probs)
print(indices)
print(probs[0][indices])
if probs[0][indices[0][0]]> probs[0][indices[0][1]]:
    print("a is larger than b")
else:
    print("b is larger than a")
    
top_3 = np.argsort(probs,axis=1)[:, -3:]
print(top_3)
class_probs = np.take_along_axis(probs, top_3, axis=1)
print(class_probs)

print(f"The test sample {test_image} ")
print("Top three Predicted classes and their corresponding probabilties\n")
for j in range(3):
        class_idx = top_3[0][2-j]
        class_prob = class_probs[0][2-j]
        print(f"\tClass {class_idx}: {class_prob:.5f}")
# print(f"Actual class to which the test sample belongs to {}  ")�


1/1 [==============================] - 0s 17ms/step
[[0. 1. 0.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1. 0.]]
1.0
[[0 2 1]]
[[0. 0. 1.]]
b is larger than a
[[0 2 1]]
[[0. 0. 1.]]
The test sample [[[[227. 154.  99.]
   [220. 147.  92.]
   [229. 156. 101.]
   ...
   [ 60.  28.  13.]
   [ 63.  35.  23.]
   [ 58.  31.  20.]]

  [[228. 155. 102.]
   [224. 151.  98.]
   [230. 157. 104.]
   ...
   [ 56.  24.   9.]
   [ 62.  32.  21.]
   [ 56.  29.  18.]]

  [[218. 145.  94.]
   [236. 163. 112.]
   [231. 158. 107.]
   ...
   [ 64.  30.  18.]
   [ 63.  30.  21.]
   [ 55.  26.  18.]]

  ...

  [[235. 137. 102.]
   [226. 116.  79.]
   [208. 103.  73.]
   ...
   [230. 172. 126.]
   [224. 162. 111.]
   [226. 146.  95.]]

  [[229. 130.  91.]
   [219. 109.  76.]
   [198.  98.  75.]
   ...
   [236. 165. 121.]
   [231. 155. 106.]
   [229. 148.  95.]]

  [[227. 128.  89.]
   [217. 107.  74.]
   [185.  85.  62.]
   ...
   [235. 164. 120.]
   [232. 156. 107.]
   [231. 150.  97.]]]] 
To

In [28]:
print(prediction)

moderate


In [29]:
print(result)

[[0. 1. 0.]]
